### PR TITLE
dir: do not compare enums using the preprocessor

### LINKED ISSUE #2003: Build doesn't work on Ubuntu 20.20
No CMake flags, CMake successful

CMake Output:
```
-- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
Git commit hash: v4.0.0-274-gdd3bae8c
Compiling with SSL support
OpenSSL include dir: /usr/include
OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;ssl;crypto
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl
 GENCERTS = 1
Generating SSL Certificates for the test-server...
Generating a RSA private key
......+++++
................................+++++
writing new private key to '/home/appstack/libwebsockets/build/libwebsockets-test-server.key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:SUCCESSFULLY generated SSL certificate
DIR /home/appstack/libwebsockets/build CMP /home/appstack/libwebsockets/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/appstack/libwebsockets/build
```

Errors on make:

```
[  1%] Building C object lib/CMakeFiles/websockets_shared.dir/misc/dir.c.o
/home/appstack/libwebsockets/lib/misc/dir.c:152:5: error: 'DT_BLK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
    ^
/usr/include/dirent.h:108:18: note: expanded from macro 'DT_BLK'
# define DT_BLK         DT_BLK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:152:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:5: error: 'DT_CHR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
    ^
/usr/include/dirent.h:104:18: note: expanded from macro 'DT_CHR'
# define DT_CHR         DT_CHR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:5: error: 'DT_DIR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
    ^
/usr/include/dirent.h:106:18: note: expanded from macro 'DT_DIR'
# define DT_DIR         DT_DIR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:5: error: 'DT_FIFO' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
    ^
/usr/include/dirent.h:102:18: note: expanded from macro 'DT_FIFO'
# define DT_FIFO        DT_FIFO
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:5: error: 'DT_LNK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
    ^
/usr/include/dirent.h:112:18: note: expanded from macro 'DT_LNK'
# define DT_LNK         DT_LNK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:5: error: 'DT_SOCK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
    ^
/usr/include/dirent.h:114:18: note: expanded from macro 'DT_SOCK'
# define DT_SOCK        DT_SOCK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
```

### PR DESCRIPTION
**Pull request by orgads**
It is invalid.

Amends commit 886a588963f61045114c3e23512425e0ca20a1bd.

Fixes #2003

### CODE REVIEW

**Comment by orgads** [comment]
I'm not sure if that was the intention.

**Comment by lws-team** [comment]
Thanks, it's pushed on master and v4.1-stable.  I had to increase the size of `type` to unsigned int.

**Comment by orgads** [comment]
Forgot to push for v4.1-stable?

**Comment by lws-team** [comment]
I had to fix an earlier patch and left your two patches popped... it's pushed now.

**Pull request closed without merging**
