### PR TITLE
mingw: fix openssl linkage

### PR DESCRIPTION
**Pull request by orgads**
ws32 and friends must come after the openssl libs,
and pthread is required for openssl.

### CODE REVIEW

**Comment by orgads** [comment]
Actually the pthread part is unrelated to mingw. Do you prefer to have it as a separate commit?

**Comment by lws-team** [comment]
PREPEND is a bit too avant-garde, it doesn't exist in cmake 3.10.2 in Ubuntu bionic

```
list does not recognize sub-command PREPEND
```

**Comment by lws-team** [comment]
It seems to be happy replacing those with INSERT ... 0 ...

**Comment by orgads** [comment]
Done

**Comment by lws-team** [comment]
Thanks it's pushed on master and v4.1-stable (and passes CI after a brief pause to upgrade the CI machine SSD)

**Pull request closed without merging**
