### PR TITLE
PKCS#7 padding added to JWE's AES-CBC

### PR DESCRIPTION
**Pull request by dzakarias-verimatrix**
This pull request contains 2 commits:

- 7c32854 is adding PKCS#7 padding/unpadding to AES-CBC in JWE. Also fixes the JWE minimal example in the case enc is one of the AES-CBC variants. Note that only the OpenSSL version of lws_genaes_destroy has been fixed, I didn't touch mbedtls.

- d8a624d modifies lws_jwe_render_compact() to always return a negative value in case of an error. Previously if rendering stopped because of a small buffer, if returned the size of the buffer, which seems misleading to me.

### CODE REVIEW

**Comment by lws-team** [comment]
Thanks... d8a6 is definitely good as it is, for the other patch I modified it a bit for style, and made the padding size define public with a slightly different name so the example could use it to add padding space rather than "32".

AFAICS mbedtls takes the approach its aes cbc only works on full blocks... the gencrypto selftests including genaes still work on openssl or mbedtls after this patch.

Please check HEAD on master and make sure that still makes sense to / works for you.

**Comment by lws-team** [comment]
Hum never mind your patch with or without my changes fails the JOSE selftests even on openssl as it is.

```
$ valgrind ./bin/lws-api-test-jose 
==2037786== Memcheck, a memory error detector
==2037786== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2037786== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==2037786== Command: ./bin/lws-api-test-jose
==2037786== 
[2020/02/10 17:04:50:8120] U: LWS JOSE api tests
[2020/02/10 17:04:50:8935] N: key_import_callback: key type 3
[2020/02/10 17:04:50:8971] N: key_import_callback: key type 2
[2020/02/10 17:04:50:8999] N: key_import_callback: key type 3
[2020/02/10 17:04:50:9008] N: key_import_callback: key type 2
[2020/02/10 17:04:50:9015] N: key_import_callback: key type 1
[2020/02/10 17:04:50:9017] N: key_import_callback: key type 1
[2020/02/10 17:04:50:9054] N: test_jwk: selftest OK
[2020/02/10 17:04:50:9058] N: 0
[2020/02/10 17:04:50:9111] N: test_jws_none: selftest OK
[2020/02/10 17:04:50:9551] N: test_jws_HS256: selftest OK
[2020/02/10 17:04:51:2448] N: test_jws_RS256: selftest OK
[2020/02/10 17:04:51:4364] N: test_jws_ES256: selftest OK
[2020/02/10 17:04:51:7955] N: test_jws_ES512: selftest OK
[2020/02/10 17:04:51:7958] N: 0
[2020/02/10 17:04:51:8012] N: test_jwe_json_complete: selftest OK
[2020/02/10 17:04:51:8581] N: lws_jose_parse: parse returned -2
[2020/02/10 17:04:51:8587] E: lws_jwe_auth_and_decrypt: JOSE parse '���VW�O)�K�V��., "enc":"A128CBC-HS256", "epk":{"crv":"P-256","kty":"EC","x":"AAk8S5f3xMMqkEJpQ' failed
[2020/02/10 17:04:51:8590] E: test_ecdhes_t1: lws_jwe_auth_and_decrypt failed
[2020/02/10 17:04:51:8593] E: test_ecdhes_t1: {"alg":"ECDH-ES","enc":"A128CBC-HS256"} selftest failed +++++++++++++++++++
[2020/02/10 17:04:52:0400] N: lws_jose_parse: parse returned -2
[2020/02/10 17:04:52:0401] E: lws_jwe_auth_and_decrypt: JOSE parse '����1F[��]��, "enc":"A192CBC-HS384", "epk":{"crv":"P-384","kty":"EC","x":"bhAklvtl5SbEbIH9k' failed
[2020/02/10 17:04:52:0401] E: test_ecdhes_t1: lws_jwe_auth_and_decrypt failed
[2020/02/10 17:04:52:0402] E: test_ecdhes_t1: {"alg":"ECDH-ES","enc":"A192CBC-HS384"} selftest failed +++++++++++++++++++
[2020/02/10 17:04:52:1105] N: lws_jose_parse: parse returned -2
[2020/02/10 17:04:52:1108] E: lws_jwe_auth_and_decrypt: JOSE parse '�*�F�
                                                                         Z' failed
[2020/02/10 17:04:52:1109] E: test_ecdhes_t1: lws_jwe_auth_and_decrypt failed
[2020/02/10 17:04:52:1109] E: test_ecdhes_t1: {"alg":"ECDH-ES","enc":"A256CBC-HS512"} selftest failed +++++++++++++++++++
[2020/02/10 17:04:52:1663] N: lws_genaes_crypt: update failed
[2020/02/10 17:04:52:2010] E: lws_jwe_auth_and_decrypt_ecdh: decrypt cek fail
[2020/02/10 17:04:52:2014] E: test_ecdhes_t1: lws_jwe_auth_and_decrypt failed
[2020/02/10 17:04:52:2015] E: test_ecdhes_t1: {"alg":"ECDH-ES+A128KW","enc":"A128CBC-HS256"} selftest failed +++++++++++++++++++
[2020/02/10 17:04:52:4864] N: lws_genaes_crypt: update failed
[2020/02/10 17:04:52:4866] E: lws_jwe_auth_and_decrypt_ecdh: decrypt cek fail
[2020/02/10 17:04:52:4867] E: test_ecdhes_t1: lws_jwe_auth_and_decrypt failed
[2020/02/10 17:04:52:4868] E: test_ecdhes_t1: {"alg":"ECDH-ES+A192KW","enc":"A192CBC-HS384"} selftest failed +++++++++++++++++++
...
```

For reference you can get my modified patch here

https://libwebsockets.org/git/libwebsockets/patch?id=f10dfda7109915b6a6126490065c347aba569f5b

I'll revert it for now so you can take a look at it.

**Comment by dzakarias-verimatrix** [comment]
The failures were caused by the following:

- trying to add unpad after decrypting a corrupt ciphertext
- tests not allocating extra bytes for padding before encryption
- me forgetting about mbedTLS

All three are fixed by the latest commit. I added macros LWS_AES_CBC_CIPHERTEXT_LEN and LWS_REQUIRED_CIPHERTEXT_LEN for better readability when allocating for ciphertext.

**Comment by lws-team** [comment]
Thanks... it's looking pretty good.  I squashed this additional patch on to the version I modified from yesterday and made some more changes for style.  With your new changes it can both pass the selftests and the lws gencrypto test apps can handle AES CBC with non-block-aligned length OK, eg

```
$ echo -n "plaintext" | ./bin/lws-crypto-jwe -e "A128KW A256CBC-HS512" -k aes128.key | ./bin/lws-crypto-jwe -d "A128KW A256CBC-HS512" -k aes128.key
```

decodes "plaintext".

Please give current master a try for your usecase.

**Comment by dzakarias-verimatrix** [comment]
Yes, it looks good. Thanks for the review!

**Comment by lws-team** [comment]
Great, thanks for the fixes.

**Pull request closed without merging**
