### PR TITLE
Fix getaddrinfo memory leak

### PR DESCRIPTION
**Pull request by hashok**
Tested with Valgrind.

### CODE REVIEW

**Comment by netrounds-joakim** [comment]
@hashok Did you test it with valgrind with one of the testapps? It would be nice to have a test program to catch stuff like this that can be run by the continous integration scripts... So if you have that, it would be nice to include.

**Comment by hashok** [comment]
@netrounds-joakim No, I tested with my own "big" app which I can't share. But it should be easy to modify an existing testapp (if such exist) to catch this error - just call libwebsockets_get_peer_addresses() for IPv4 context and it will leak without this fix.

**Comment by select-this** [comment]
Good catch; I just spotted that in the project I'm working on as well.

**Comment by warmcat** [comment]
Great job, it's pushed thanks.

**Pull request closed without merging**
