### PR TITLE
libuv: fix idle being stopped when there is still pending stuff

### PR DESCRIPTION
**Pull request by lonnywong**
Related issues:
- https://github.com/tsl0922/ttyd/issues/1239
- https://github.com/warmcat/libwebsockets/issues/1768#issuecomment-1814289921

### CODE REVIEW

**Comment by lws-team** [comment]
That looks very reasonable, thanks a lot for going through it -- I pushed it on main + v4.3-stable

**Comment by lonnywong** [comment]
@lws-team Thanks for your help.

Looking forward to the release of new versions.

**Comment by lonnywong** [comment]
@lws-team Any new releases planned? We got another issue https://github.com/tsl0922/ttyd/issues/1254, and it works with `v4.3-stable` branch.

**Comment by lws-team** [comment]
OK... v4.3.3 is tagged out.

**Pull request closed without merging**
