### PR TITLE
Report unauthorized error when 401 is received, instead of "HS: ACCEPT missing"

### PR DESCRIPTION
**Pull request by joelittlejohn**
See #1200 

The two changes included here are as discussed:

1. Check the response status before checking for the Sec-WebSocket-Accept header 

2. Return `HS: ws upgrade unauthorized` as the failure message when 401 is received.

@lws-team I opted to add a specific message here to avoid issues with having to format a new string to contain the response status, or finding an appropriate place to put it that would be freed (I couldn't find one). I considered creating a new fixed length char array to hold cce writing a formatting string to it (e.g. snprintf), but in the end just opted to keep this simple. Let me know your thoughts and I can revisit if necessary.

### CODE REVIEW

**Comment by lws-team** [comment]
Nice job, thanks, it's pushed on master + v2.4-stable.

**Comment by joelittlejohn** [comment]
Thanks Andy, amazing response! :slightly_smiling_face:

**Comment by joelittlejohn** [comment]
Of course you know what my next question is going to be (sorry!)... any idea when you'll cut 2.4.2?

**Comment by lws-team** [comment]
It's tagged out... enjoy

**Comment by joelittlejohn** [comment]
Ahh, sorry @lws-team there is a bug in my patch which is causing valid connections to fail!

This line:
```
if (p && strncmp(p, "401", 3)) {
```
in client.c should instead be:
```
if (p && strncmp(p, "401", 3) == 0) {
```

:man_facepalming:

**Comment by lws-team** [comment]
Well, nothing that can't be fixed with a ninja retag.

**Comment by joelittlejohn** [comment]
Andy, we're seeing that Homebrew has the old 2.4.2 and the old sha. Would it be possible to cut a new version?

**Pull request closed without merging**
