### PR TITLE
gcc format strings: couple more

### PR DESCRIPTION
**Pull request by mmilata**
Found with gcc-4.7 on mipsel.

See #811 for master branch (the one in handshake.c is already included).

### CODE REVIEW

**Comment by lws-team** [comment]
The handshake.c one is already in current master... I added the first PR in permessage-deflate only.

**Comment by mmilata** [comment]
Sorry, forgot to mention that this one is against `v2.1-stable`.

**Comment by lws-team** [comment]
Ah I see... it's also pushed on v2.1-stable now, thanks.

**Comment by mmilata** [comment]
Thank you!

**Pull request closed without merging**
