### PR TITLE
fix LWS_USE_LIB(E|U)V

### PR DESCRIPTION
**Pull request by wangchuan3533**

### CODE REVIEW

**Comment by lws-team** [comment]
What is it we're trying to fix here?  LWS_WITH_LIBUV / EV already works OK without this change (as you see the change breaks appveyor + travis in fact).

**Comment by wangchuan3533** [comment]
the lib cannot compile with the following commands
`
mkdir build && cd build
cmake -DLWS_USE_LIBUV ..
make
`
$ cmake -DLWS_USE_LIBUV=ON ..
-- The C compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE=''
-- Found Git: /usr/local/bin/git  
Git commit hash: wangchuan@localhost-v2.0.2-16-gd7fb6ad
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Success
-- Performing Test LWS_HAVE___inline__
-- Performing Test LWS_HAVE___inline__ - Success
-- Performing Test LWS_HAVE___inline
-- Performing Test LWS_HAVE___inline - Success
-- Looking for bzero
-- Looking for bzero - found
-- Looking for fork
-- Looking for fork - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for execvpe
-- Looking for execvpe - not found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for getloadavg
-- Looking for getloadavg - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for in6addr.h
-- Looking for in6addr.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for zlib.h
-- Looking for zlib.h - found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Performing Test LWS_HAVE_VISIBILITY
-- Performing Test LWS_HAVE_VISIBILITY - Success
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
zlib include dirs: /usr/include
zlib libraries: /usr/lib/libz.dylib
Compiling with SSL support
-- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8}") 
OpenSSL include dir: /usr/include
OpenSSL libraries: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl
Generating SSL Certificates for the test-server...
SUCCESSFULLY generated SSL certificate
Generating API documentation
-- Looking for RPMTools... - rpmbuild NOT FOUND
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = ON (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_USE_POLARSSL = OFF (PolarSSL replacement for OpenSSL)
 LWS_USE_MBEDTLS = OFF (mbedtls (nee Polarssl) replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_USE_LIBEV = 
 LWS_USE_LIBUV = ON
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_MBED3 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 32
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_HAVE_SSL_CTX_set1_param = 
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES = 
 PLUGINS = 
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/wangchuan/git/libwebsockets/build
$ make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  2%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  4%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  5%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[  7%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[  8%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[ 10%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[ 11%] Building C object CMakeFiles/websockets.dir/lib/context.c.o
[ 12%] Building C object CMakeFiles/websockets.dir/lib/alloc.c.o
[ 14%] Building C object CMakeFiles/websockets.dir/lib/header.c.o
[ 15%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 17%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 18%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 20%] Building C object CMakeFiles/websockets.dir/lib/ssl.c.o
[ 21%] Building C object CMakeFiles/websockets.dir/lib/ssl-server.c.o
[ 22%] Building C object CMakeFiles/websockets.dir/lib/ssl-client.c.o
[ 24%] Building C object CMakeFiles/websockets.dir/lib/sha-1.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-unix.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 28%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 30%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
[ 31%] Building C object CMakeFiles/websockets.dir/lib/extension-permessage-deflate.c.o
[ 32%] Linking C static library lib/libwebsockets.a
[ 32%] Built target websockets
Scanning dependencies of target test-server-extpoll
[ 34%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server.c.o
[ 35%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server-http.c.o
[ 37%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server-dumb-increment.c.o
[ 38%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server-mirror.c.o
[ 40%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server-status.c.o
[ 41%] Building C object CMakeFiles/test-server-extpoll.dir/test-server/test-server-echogen.c.o
[ 42%] Linking C executable bin/libwebsockets-test-server-extpoll
Undefined symbols for architecture x86_64:
  "_lws_feature_status_libuv", referenced from:
      _lws_create_context in libwebsockets.a(context.c.o)
  "_lws_libuv_accept", referenced from:
      _lws_client_connect_2 in libwebsockets.a(client-handshake.c.o)
      _lws_adopt_socket_vhost in libwebsockets.a(server.c.o)
  "_lws_libuv_closehandle", referenced from:
      _lws_close_free_wsi in libwebsockets.a(libwebsockets.c.o)
  "_lws_libuv_destroyloop", referenced from:
      _lws_context_destroy in libwebsockets.a(context.c.o)
  "_lws_libuv_init_fd_table", referenced from:
      _lws_plat_init in libwebsockets.a(lws-plat-unix.c.o)
  "_lws_libuv_io", referenced from:
      __lws_change_pollfd in libwebsockets.a(pollfd.c.o)
      _remove_wsi_socket_from_fds in libwebsockets.a(pollfd.c.o)
      _lws_plat_insert_socket_into_fds in libwebsockets.a(lws-plat-unix.c.o)
      _lws_plat_delete_socket_from_fds in libwebsockets.a(lws-plat-unix.c.o)
  "_lws_libuv_run", referenced from:
      _lws_plat_service_tsi in libwebsockets.a(lws-plat-unix.c.o)
  "_lws_uv_sigint_cb", referenced from:
      _lws_create_context in libwebsockets.a(context.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libwebsockets-test-server-extpoll] Error 1
make[1]: *** [CMakeFiles/test-server-extpoll.dir/all] Error 2
make: *** [all] Error 2

**Comment by lws-team** [comment]
Right... but -DLWS_WITH_LIBUV=1 works fine, right?

That's the correct name of the related cmake option

https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L69

**Comment by wangchuan3533** [comment]
I figured it out
it should be ```cmake -DLWS_WITH_LIBUV=ON ..```

**Comment by lws-team** [comment]
Ok no worries.

**Pull request closed without merging**
