### PR TITLE
Esp32 on windows

### PR DESCRIPTION
**Pull request by benjamind**
This revises the ESP32 build to work reliably under Windows (MSYS2) shell.

Have also moved the check for `genromfs` and `xxd` from the `CMakeLists.txt` to the `esp32.mk`. This way the library can be used without the dependency on these tools, and only when its actually being used to pack the binaries is it required. This will allow users to opt out of the `genromfs` packing in their standalone implementations if they want. I will add instructions to the `lws-esp32-factory` and `lws-esp32-test-server-demos` projects detailing how to install these dependencies under Windows.

Also added some minor documentation cleanup, exposing the ESP32 and ESP8266 readmes in the doxygen'd output, adding `doc` to `.gitignore` and standardizing use of whitespace in the `README.build.md`.

### CODE REVIEW

**Comment by lws-team** [comment]
Thanks, I added these, but I moved the patches around a bit to better summarize what they are doing.

Aso on the "fixes esp32 build", the weirdo paths `../../../..` etc are there for a reason, the depth of the dir the project itself and esp-idf are in is actually unknown.  We already had a bug where it was too far down

https://github.com/warmcat/libwebsockets/issues/956

so just trimming this to two levels won't fly.  So I removed that part of the patch and confirmed it still works here at least.  Please check the meddling around didn't break anything for you.

**Comment by benjamind** [comment]
Hmm, I see.

I will investigate the path issue a little more. I think there is probably
an environment variable we can pass down to avoid this crazy path hack.
Does not seem right to be abusing the relative paths like this.

**Comment by lws-team** [comment]
If you want to provide a better fix, it's welcome.  Whether "right" or not, it works, which is better than the alternative :-)

**Comment by benjamind** [comment]
Agreed a working solution is better than a non-working solution ;-)

However, if you put something like this in, it will keep coming up as an issue when future maintainers see that huge collection of seemingly incorrect parent folder paths.

I spent a while looking through the build system and I think the cleanest way of implementing this is to add a `Makefile.projbuild` to the `libwebsockets` component. This file includes the single line:
```
CPPFLAGS += -I$(BUILD_DIR_BASE)/libwebsockets/include
```
This will then add the include folder to the project global `CPPFLAGS` so the headers will be properly found across the project.

Short of re-arranging the build so that the include files get copied back into the components folder after cmake completes (and the associated clean targets are added) I think this is better than the fragile path we have now.

**Comment by benjamind** [comment]
FYI, without the above fix regarding the include path the current master of `libwebsockets` does not compile on windows. The issue is that the resolved relative path ends up containing a double slashed path that does not resolve properly, e.g. `'../../../../../../../..//d/my/foo/dir/'`

**Comment by lws-team** [comment]
Yeah... that works here too thanks.  There's a lot of esp32-specific junk appearing at the top level of lws to keep esp build system happy.  No other platform requires that.

Anyway I added it and I will push it later thismorning along with a WIP of the -factory changes so we are testing the same thing.

PS '../../../../../../../..//d/my/foo/dir/' good old windows

**Comment by benjamind** [comment]
Agreed on the esp32-specific junk. I think this could be resolved by changing the way the `libwebsockets` repository is included into `esp-idf` projects.

For other libraries I have made a shim component which lives in the `/components` folder that then reached out to a `../vendor/my-foo-library` to do compilation of the vendor library. This works pretty well, and you can then keep all the `esp-idf` specific scripts, makefiles and so on out of the core library.

**Pull request closed without merging**
