### PR TITLE
added no-cache handling

### PR DESCRIPTION
**Pull request by horchi**

### CODE REVIEW

**Comment by horchi** [comment]
added no-cache handling

**Comment by lws-team** [comment]
Thanks, it's pushed on main.

**Comment by horchi** [comment]
Thanks!

I have not counted up a version in the patch because I do not know the procedure. Hope that was not wrong. Can I now still use one of the LWS_LIBRARY_VERSION* constants to query whether the feature is there?

**Comment by lws-team** [comment]
As a convenience I updated the patch to define LWS_FEATURE_MOUNT_NO_CACHE, you can test if that #if defined().

**Comment by horchi** [comment]
Perfekt, many thanks!!

**Pull request closed without merging**
