### PR TITLE
port test-server-libuv.c from libev to libuv

### PR DESCRIPTION
**Pull request by alexhultman**
~~This works and have no Valgrind issues even on disconnect, but there are issues when closing down the server. You need to kill the process because it doesn't shut down correctly.~~

Actually I was connecting to the wrong server (mega facepalm). When I actually connect to this test server I can trigger the valgrind error when disconnecting. This is good news.

### CODE REVIEW

**Comment by lws-team** [comment]
Thanks... I am in transit atm and will pull and study it later.  It sounds like it's what's needed to see the problem.

**Comment by alexhultman** [comment]
No hurry I'm going to sleep (CET time zone).

**Comment by lws-team** [comment]
I solved the basic problem I think but it needs more work, I'll continue with it.

**Comment by alexhultman** [comment]
Nice, commit when you have something to share. Then I can finish the missing signals.

**Comment by lws-team** [comment]
This is fixed and pushed now, we can close this and move to the issue to discuss further.

**Pull request closed without merging**
