### PR TITLE
mbedtls: fix issue about memory leak

### PR DESCRIPTION
**Pull request by lucas-law**
https://github.com/warmcat/libwebsockets/issues/3177

### CODE REVIEW

**Comment by lws-team** [comment]
Thanks, it's pushed on v4.3-stable and main

**Comment by simon0356** [comment]
Hello Andy, Lucas,

I noticed that the mbedtls freeing is not called at the same moment on FreeRTOS nor Unix plateform.
Is this a mistake or is there a good reason ? 
I could do a PR to put the free in lws_plat_context_late_destroy for freertos to do this in the same way.

Thanks
Simon

**Comment by lws-team** [comment]
What code are we talking about with "mbedtls freeing"?  AFAIK we should only take care to destroy the entropy / rng stuff after any other mbedtls-specific allocations.  If it's happening that way already it's probably OK AFAIK,

**Comment by simon0356** [comment]
I mean mbedtls_ctr_drbg_free and mbedtls_entropy_free are called in lws_plat_context_early_destroy for freertos and lws_plat_context_late_destroy for unix.

**Comment by lws-team** [comment]
Right... yes given the only constraint is that we shouldn't do any mbedtls business after destroying the entropy stuff it's better to do as you suggest.  It's unlikely to break anything AFAIK doing it a bit later.

**Pull request closed without merging**
