### PR TITLE
Remove unneeded #include <stdint.h>

### PR DESCRIPTION
**Pull request by paroga**
This fixes the build for Visual Studio 2008.

### CODE REVIEW

**Comment by lws-team** [comment]
It may not be needed on vs2008, but it is needed on whatever vs appveyor uses (2014 or such), as you can see from the appveyor fail log on the link above.  So it is not useless cruft per se.

Patching around it is fine, but it will need to be made conditional on, eg, > VS2008.

**Comment by lws-team** [comment]
Thanks, that works too: it's pushed.

**Comment by paroga** [comment]
Can you push it on the stable branch too?

**Comment by lws-team** [comment]
Sure... it's done thanks.

**Comment by paroga** [comment]
thx!

**Pull request closed without merging**
