### PR TITLE
Haiku: initial platform support

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
There is a minor hack related to #1032

**Comment by lws-team** [comment]
Thanks, I pushed it after snipping the "hack" bit off.

If there's anything special Haiku users should do or know, please let me know so we can add it somewhere in the docs.

**Comment by kallisti5** [comment]
Thanks!  It builds and the tests function normally.

**Comment by kallisti5** [comment]
actually... something seems wrong. I think there are a bunch of LWS_HAVE_XXX checks now above the function tests.

**Comment by lws-team** [comment]
Yeah I moved them already.  But it's dying because it generates

```
/* Define to rpl_malloc if the replacement function should be used. */
#define malloc

/* Define to rpl_realloc if the replacement function should be used. */
#define realloc
```

in build/lws_config_private.h now

**Comment by kallisti5** [comment]
all reasons I was afraid to touch it :-)

* set LIB_LIST   ( no dependencies)
* platform libraries ( no dependencies)
* libs : zlib, ssl,  (HAVE_OPENSSL_ECDH_H)libev, libuv, libevent, sqlite, httpproxy
* set REQUIRED_LIBS from LIB_LIST
* function checks (set LWS_HAVE) (depends on platform libraries)
* SSL function checks

**Comment by lws-team** [comment]
Yeah... people want to use lws in a lot of situations... it's quite flexible and that shows up in CMakeLists.txt.  What should we do... say no to people who turn up wanting to add support to some OS nobody else wanted for 7 years :-) ?  It's not helping telling me how much you're holding your nose.

The current situation looks like a cmake bug actually... at least I can't find any other reason those two cmakedefines are defined instead of commented.  unset(malloc) and unset(realloc) makes it work... maybe something else sets these somewhere...

**Comment by lws-team** [comment]
OK I am removing the 1032 patch and adapting your patch to be as it was posted.

You never explained what was actually wrong with looking for toolchain / stdc defines before we added lws-specific libs; every other platform is OK with that.  If I am looking for `malloc`, I don't need to have openssl or whatever.  And there's plenty of code in CMakeLists.txt that legitimately wants to know the results of those tests earlier.

If your platform has some funny requirement (perhaps cmake doesn't add default paths correctly for it as it does the other platforms) then what you called a "hack" in your patch is actually the correct solution.

**Comment by kallisti5** [comment]
>  It's not helping telling me how much you're holding your nose.

Err, I didn't say or imply that at all. It's a lot of complex library resolution. You should see some of the have statements in mesa's code which supports haiku/irix/aix/solaris/linux/bsd/windows/cygwin/etc :-)

The need is our getifaddrs exists in libnetwork.so and the build is broken without it included. We can call the change as-is the solution. I just thought adding network to the cmake required libraries, then resetting it later might seem "hackish" since the pattern of defining platform libraries before performing function exists checks would ease future platform portability.

**Pull request closed without merging**
