### PR TITLE
Fix v4.3 memleak

### PR DESCRIPTION
**Pull request by lucas-law**
Fix this issue: https://github.com/warmcat/libwebsockets/issues/3177

### CODE REVIEW

**Comment by lws-team** [comment]
I guess you actually just want to push this?

https://github.com/warmcat/libwebsockets/pull/3264/commits/e664fc2928faeba56913baeb016f6529aa119c8d

**Comment by lucas-law** [comment]
Yes, I'm sorry that I made a mistake in sync remote main to current branch.

**Comment by lws-team** [comment]
No worries, just wanted to confirm that was it.  git wants you to rebase your patch on the same tree you're pushing to, ie, main, then it can understand you just added one patch on top.

**Comment by lucas-law** [comment]
Should I need to reopen this PR?

**Comment by lws-team** [comment]
Open state of it doesn't really matter, I am watching it, we can post on it etc.

To retry the push, I think all you need to do is update your remote branch  [lucas-law:fix-v4.3-memleak](https://github.com/lucas-law/libwebsockets/tree/fix-v4.3-memleak) and what's shown in this issue will update.

**Comment by lucas-law** [comment]
Ok, my changes just based on v4.3 tag.

**Pull request closed without merging**
